# Generated by Django 4.0.3 on 2022-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(help_text='账户', max_length=60, null=True)),
                ('nickname', models.CharField(blank=True, help_text='用户昵称', max_length=60, null=True)),
                ('password', models.CharField(help_text='账号密码', max_length=255, null=True)),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, help_text='性别信息[1: 男, 2: 女]')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=120, null=True)),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=24, null=True)),
                ('avatar', models.CharField(blank=True, help_text='头像信息', max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '锁定'), (1, '正常')], default=1, help_text='用户状态[0: 被锁定, 1: 正常]')),
                ('created_date', models.PositiveIntegerField(help_text='创建时间', null=True)),
                ('updated_date', models.PositiveIntegerField(help_text='更新时间', null=True)),
            ],
        ),
    ]
